# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  tables: true

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Bidstream Optimizer
tagline:          'Bidstream Optimizer Documentation'
description:      'Onboarding docs for <a href="https://authenticated.digital" target="_blank">Bidstream Optimizer</a>.'
url:              https://damonreeve.github.io/optimizer-docs/
baseurl:          /optimizer-docs/

author:
  name:           'Damon Reeve'
  url:            https://github.com/damonreeve

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/damonreeve/optimizer-docs/
